module Fcmpush
  module Httpx
    V1_ENDPOINT_PREFIX: String
    V1_ENDPOINT_SUFFIX: String
    TOPIC_DOMAIN: String
    TOPIC_ENDPOINT_PREFIX: String
    TOPIC_ENDPOINT: String

    class Client
      @configuration: Configuration
      @options: untyped

      @path: String

      @project_id: String?

      attr_reader access_token: String
      attr_reader access_token_expiry: Time
      attr_reader configuration: Configuration
      attr_reader domain: String
      attr_reader httpx: ::Httpx::Client

      attr_reader path: String

      def push: -> HTTPX::Response

      def subscribe: -> HTTPX::Response

      def unsubscribe: -> HTTPX::Response

      def v1_authorize: -> Hash[String, String]

      private

      def refresh_access_token: -> untyped
    end
  end
end
