module Fcmpush
  module Httpx
    class Configuration
      @json_key_io: untyped
      @read_timeout: Integer
      @write_timeout: Integer
      @connect_timeout: Integer
      @scope: Array[String]

      attr_reader json_key_io: untyped
      attr_accessor scope: Array[String]
      attr_accessor read_timeout: Integer
      attr_accessor write_timeout: Integer
      attr_accessor connect_timeout: Integer
    end
  end
end
